### ISSUE TITLE
error running cwe in ghidra

### ISSUE THREAD

**Issue by hmne** [fkie-cad/cwe_checker#372] opened 2023-01-19 03:58 UTC
hi i have ghidra 10.1.2 public and i did compile cwe_checker-0.6 and copied cwe_checker_ghidra_plugin.py to ~/ghidra_10.1.2/Ghidra/Features/Python/ghidra_scripts

```
cwe_checker_ghidra_plugin.py> Running...
Traceback (most recent call last):
  File "~/ghidra_10.1.2/Ghidra/Features/Python/ghidra_scripts/cwe_checker_ghidra_plugin.py", line 63, in <module>
    main()
  File "~/ghidra_10.1.2/Ghidra/Features/Python/ghidra_scripts/cwe_checker_ghidra_plugin.py", line 50, in main
    warnings = get_cwe_checker_output()
  File "~/ghidra_10.1.2/Ghidra/Features/Python/ghidra_scripts/cwe_checker_ghidra_plugin.py", line 42, in get_cwe_checker_output
    return json.load(json_file)
  File "~/ghidra_10.1.2/Ghidra/Features/Python/data/jython-2.7.2/Lib/json/__init__.py", line 286, in load
    return loads(fp.read(),
  File "~/ghidra_10.1.2/Ghidra/Features/Python/data/jython-2.7.2/Lib/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "~/ghidra_10.1.2/Ghidra/Features/Python/data/jython-2.7.2/Lib/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "~/ghidra_10.1.2/Ghidra/Features/Python/data/jython-2.7.2/Lib/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
cwe_checker_ghidra_plugin.py> Finished!
```
the test file is 20KB 
[rev50_linux64-bit.zip](https://github.com/fkie-cad/cwe_checker/files/10453360/rev50_linux64-bit.zip)

**Comment by Enkelmann** [comment] 2023-01-19 07:18
The Ghidra plugin script is currently not as user-friendly as one would intuitively expect. To quote the usage instructions from the script:
```
# Usage:
# - Copy this file into the Ghidra scripts folder
# - Run the cwe_checker on a binary and save its output as a json file, e.g. with
#   "cwe_checker BINARY --json --out output.json"
# - Open the binary in Ghidra and run this file as a script. Select the generated json file when prompted.
```
I suspect you used the binary itself as an input into the script instead of the JSON output file. Or you forgot the `--json` flag when generating the JSON output file. When I tried to reproduce the problem I got exactly your error message when using the binary itself as input into the script, but everything worked fine when following the usage instructions.

**Comment by Enkelmann** [comment] 2023-06-21 11:06
Closing. I never got an answer from the issue author, so I have to assume that the issue is solved.

**Closed by Enkelmann** 2023-06-21 11:06 UTC
