### ISSUE TITLE
missing field `string_symbols`

### ISSUE THREAD

**Issue by sh4m2hwz** [fkie-cad/cwe_checker#280] opened 2022-01-12 09:25 UTC
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `string_symbols`", line: 0, column: 0)', src/cwe_checker_lib/src/checkers/cwe_78.rs:104:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

https://github.com/fkie-cad/cwe_checker/blob/41f10fa1256728e84eabefaa9cd7d0201432fbbf/src/cwe_checker_lib/src/checkers/cwe_78.rs#L104

rather, this is due to the fact that the binary is stripped

**Comment by Enkelmann** [comment] 2022-01-12 11:57
Whether the binary is stripped or not should not make a difference for the check. This looks more like a bug in the cwe_checker. Can you provide a binary where this happens? Then I could try to find the bug.

**Comment by Enkelmann** [comment] 2023-06-21 10:59
Closing, since this issue is quite old and we never got a binary where we could reproduce the issue.

**Closed by Enkelmann** 2023-06-21 10:59 UTC
