### ISSUE TITLE
Panic due to "missing field `tid`"

### ISSUE THREAD

**Issue by hrantzsch** [fkie-cad/cwe_checker#161] opened 2021-03-29 13:19 UTC
I tried to run the docker image on the [botan](https://github.com/randombit/botan) cli executable. Unfortunately, after running for a while it panics with
```
$ docker run --rm -v $(pwd)/botan:/input fkiecad/cwe_checker /input
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `tid`", line: 80734887, column: 9)', src/caller/src/main.rs:300:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Checking a very simple hello-world example works fine, though.

I'm on Manjaro Linux with kernel `5.10.23-1`.

**Comment by Enkelmann** [comment] 2021-04-06 06:37
I am on vacation right now, so I won't be able to look at it until next week. I know this kind of error message from a bug that we fixed a while ago. It is probably a special case of that bug that we missed.

**Comment by Enkelmann** [comment] 2021-04-12 07:03
The botan binary installed on my system (also Manjaro) did not produce an error. Which probably means that your binary had a different build environment. Can you provide the affected binary? I have found an example of a busybox binary producing the same error message, but it is not guaranteed that the same root cause as for your binary is responsible.

**Comment by hrantzsch** [comment] 2021-04-12 08:41
Yes, I should have mentioned I built it locally on Botan's development branch. Here's the binary: https://shared-link.bdrive.cloud/shared/b2184a3d-e21f-4a2e-be77-7674a0917db2#cc2abadba60f72f7c9cc999dd1670a191cd9312a382a2e8b90b4b1a5b2853dac

It was built using
```
./configure.py --cc-bin=/usr/bin/g++ --cxxflags="$CXXFLAGS --std=c++17" --build-targets=static,cli
make
```

**Comment by Enkelmann** [comment] 2021-04-12 09:04
Thanks! I can reproduce it on my side. We are on it.

**Comment by Enkelmann** [comment] 2021-04-13 11:49
Short update: This bug should be fixed now via #163.

But the botan binary you provided seems to be affected by another bug (probably unrelated to the fixed bug), which we are currently trying to fix.

**Closed** 2021-04-19 05:12 UTC

**Comment by Enkelmann** [comment] 2021-04-19 05:19
Now the cwe_checker runs correctly on the botan binary. :-) The log messages suggest that we still have trouble understanding the binary correctly in some places. But I think these are related to the fact that it is written in C++. Right now, we focus on improving analysis quality for binaries written in C, so it may take a while before we come around to take a deeper look at C++-related issues.

**Comment by hrantzsch** [comment] 2021-04-19 06:58
That's great, thank you!
