### ISSUE TITLE
Failed to start docker.

### ISSUE THREAD

**Issue by jhye0n** [fkie-cad/cwe_checker#202] opened 2021-07-08 06:02 UTC
Refer to the README and run Docker with the following command.

But I get an error. do you know about this
➜  ~ sudo docker run --rm -v <Binary Path>:/input fkiecad/cwe_checker:stable /input

Execution of Ghidra plugin failed: Process was terminated.
INFO  REPORT: Save succeeded for file: /input (HeadlessAnalyzer)  
INFO  REPORT: Post-analysis succeeded for file: /input (HeadlessAnalyzer)

**Comment by Enkelmann** [comment] 2021-07-08 06:21
According to the error message the Ghidra plugin (which we use to extract the disassembly of a binary) failed. The two `INFO REPORT` lines are the last two lines of the output of the Ghidra plugin, which, unfortunately, do not contain any useful information as to what the cause of the error is in this case.

Can you provide the binary for which the error occured? Or at least some information on the type of the binary?

**Comment by Enkelmann** [comment] 2021-07-26 05:16
I am closing this, because I cannot help without further information. Feel free to reopen if you can provide more details.

**Closed by Enkelmann** 2021-07-26 05:16 UTC
