### ISSUE TITLE
failed to build a project: Tag_sexp

### ISSUE THREAD

**Issue by frakman1** [fkie-cad/cwe_checker#61] opened 2020-05-19 18:20 UTC
I get a lot of these type of errors when analyzing ARM 32 binaries cross compiled for a Broadcom type chipset. I navigate to my cross-compiled root file system and run this:
```bash
$docker run -it -v `pwd`:/opt fkiecad/cwe_checker /bin/bash
```

```bash
bap@ca1c05ffa64c:~/cwe_checker$ cwe_checker --version
0.3-dev
bap@ca1c05ffa64c:~/cwe_checker$ file /opt/ot-cli
/opt/ot-cli: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.16, stripped
bap@ca1c05ffa64c:~/cwe_checker$ cwe_checker /opt/ot-cli
INFO: Using standard configuration...
failed to build a project: Tag_sexp
validation errors
view must not be empty
value 0x57A23:32u < bound 0x57A24:32u

Backtrace:
Raised at file "src/error.ml" (inlined), line 9, characters 14-30
Called from file "src/or_error.ml", line 72, characters 17-32
Called from file "lib/bap_disasm/bap_disasm_driver.ml", line 470, characters 34-50
Called from file "lib/monads/monads_monad.ml", line 1010, characters 60-63
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1020, characters 21-27
Called from file "lib/knowledge/bap_knowledge.ml", line 2671, characters 10-45
Called from file "lib/bap_types/bap_toplevel.ml", line 54, characters 8-38
Called from file "lib/bap_types/bap_toplevel.ml", line 59, characters 2-15
Called from file "lib/bap/bap_project.ml", line 51, characters 6-130
Called from file "lib/bap/bap_project.ml", line 254, characters 25-51
Called from file "lib/bap/bap_project.ml", line 280, characters 12-47
Called from file "src/or_error.ml", line 64, characters 9-15
```

I see this error with any binary linked to `busybox`. I also noticed that files with no symbols return this error. Does this mean that `cwe_checker` only works with binaries that have not been stripped of symbols?

**Comment by Enkelmann** [comment] 2020-05-20 05:35
The cwe_checker should work just fine with stripped binaries. This is an error in BAP trying to disassemble the file. Since we currently work with an outdated snapshot of the BAP master branch, it is possible, that this is a bug which is already fixed in the current master branch of BAP. I will update the BAP version in our docker image and then we can check whether this already solves your problem.

**Comment by Enkelmann** [comment] 2020-05-20 12:41
Ok, the docker image is updated. Could you try your binary again and see if the error is still there? If yes, please also try
```
bap BINARY -d
```
to confirm whether the error already occurs during disassembly by BAP.

**Comment by frakman1** [comment] 2020-05-21 03:20
Thank you. I'll try it and report back when I get results.

**Comment by frakman1** [comment] 2020-05-22 14:38
I also tried using `bap`:
```bash
bap@ee4d8b4ad9b3:~/cwe_checker$ bap /opt/ot-cli -d
failed to build a project: Tag_sexp
validation errors
view must not be empty
value 0x57A23:32u < bound 0x57A24:32u

Backtrace:
Raised at file "src/error.ml" (inlined), line 9, characters 14-30
Called from file "src/or_error.ml", line 72, characters 17-32
Called from file "lib/bap_disasm/bap_disasm_driver.ml", line 466, characters 34-50
Called from file "lib/monads/monads_monad.ml", line 1010, characters 60-63
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1010, characters 38-42
Called from file "lib/monads/monads_monad.ml" (inlined), line 1005, characters 29-34
Called from file "lib/monads/monads_monad.ml", line 1020, characters 21-27
Called from file "lib/knowledge/bap_knowledge.ml", line 2671, characters 10-45
Called from file "lib/bap_types/bap_toplevel.ml", line 54, characters 8-38
Called from file "lib/bap_types/bap_toplevel.ml", line 59, characters 2-15
Called from file "lib/bap/bap_project.ml", line 51, characters 6-130
Called from file "lib/bap/bap_project.ml", line 254, characters 25-51
Called from file "lib/bap/bap_project.ml", line 280, characters 12-47
Called from file "src/or_error.ml", line 64, characters 9-15
```

**Comment by ivg** [comment] 2020-05-22 14:55
Could you please provide us the file? Also, @Enkelmann, what version of LLVM is used in this docker image? It might be an LLVM error, also. 

@gitoleg, looping you in.

**Comment by frakman1** [comment] 2020-05-22 15:22
[ot-cli.zip](https://github.com/fkie-cad/cwe_checker/files/4668946/ot-cli.zip)

**Comment by ivg** [comment] 2020-05-22 17:05
I can confirm that the same issue is reproducible with the latest development version of bap.

```
$ bap --llvm-version
6.0
```
@gitoleg, can you take it from here? @Enkelmann, you can transfer this issue to BAP if you like.

**Comment by gitoleg** [comment] 2020-05-22 17:17
sure

**Comment by ivg** [comment] 2020-05-29 11:03
It's nontrivial so it will take some time to find it. And 2.1 is already released, so the bug is planned for 2.2.0-alpha

**Comment by ivg** [comment] 2020-06-16 14:57
@Enkelmann, will you transfer this issue to BAP? (the button is on the right side bar, after the participants, at the very bottom of the side bar).

Otherwise, we keep forgetting about it. If you don't want to transfer and prefer to keep it, then I will create an issue in BAP that will reference this one.

**Comment by Enkelmann** [comment] 2020-06-16 15:37
@ivg Looks like I cannot transfer the issue, github produces an error when I try. It seems that you need to create a new issue in BAP for it.

**Comment by ivg** [comment] 2020-06-16 15:43
No worries! Yeah, issue transferring sometimes doesn't work, especially outside of organization. I will create a proxy issue.

**Comment by Enkelmann** [comment] 2020-06-30 05:58
Closing this issue as it is handled on the BAP side. We also switched to LLVM 9 in the official docker image, which may prevent the error from occuring.

**Comment by frakman1** [comment] 2020-07-03 16:55
Does this mean that grabbing the latest `cwe_checker` will fix this problem?

**Comment by Enkelmann** [comment] 2020-07-06 05:39
I hope so. If not, please report it here.

The underlying BAP issue is at least partially fixed in the BAP master branch. Right now, the official docker image is using the stable BAP 2.1 version, so the fix is not included yet. But switching to LLVM 9 in the docker image also seemed to resolve the issue. Since I want to avoid having to depend on a snapshot of the BAP master branch, I'll postpone pulling in the fix as long as nobody reports the same error still occuring with the latest docker image of the *cwe_checker*.

**Comment by frakman1** [comment] 2020-07-06 07:32
I don't understand what I need to do to get the latest cwe_checker? I tried running `docker pull fkiecad/cwe_checker:latest` and running the test but I get the same error and it doesn't appear that the version of cwe-checker has changed (0.3-dev). What does "switching to LLVM 9 in the docker image" mean in the context of using this tool via docker?

**Comment by Enkelmann** [comment] 2020-07-06 07:53
BAP uses LLVM. Previously we had LLVM 6 installed in the docker image, now we have LLVM 9 installed in it. You can confirm that by running `bap --llvm-version` inside the docker image.

Apparently this did not fix it for you, so we have to consider switching to BAP master again. :-( I will test whether this helps first, though.

**Comment by frakman1** [comment] 2020-07-06 17:09
Thank you for the explanation. Yes, I just confirmed that `bap --llvm-version` returns `9.0` as expected. (I didn't realize that it was an independent component)

For reference, this is the current output. I no longer get a backtrace anymore:

```bash
bap@60eed0c12903:~/cwe_checker$ bap --llvm-version
9.0
bap@60eed0c12903:~/cwe_checker$ cwe_checker /opt/ot-cli
INFO: Using standard configuration...
Failed to build the project:
 Tag_sexp
validation errors
view must not be empty
value 0x57A23:32u < bound 0x57A24:32u


bap@60eed0c12903:~/cwe_checker$
```

another file gave a different error:

```bash
bap@60eed0c12903:~/cwe_checker$ cwe_checker /opt/bash
INFO: Using standard configuration...
ERROR: [cwe_checker] No configuration file provided! Aborting...
```
Am I supposed to provide a configuration file with this?

**Comment by Enkelmann** [comment] 2020-07-07 06:37
I updated the docker image `fkiecad/cwe_checker:latest` to using a snapshot of the BAP master branch again. You can check this by running `bap --version` inside the docker container, which should output something like `2.2.0-alpha+xxx`. This resolves the issue at least on the file you provided. If you can confirm, that this also resolves it on the other files you mentioned, I would be grateful. :-) And a word of warning: BAP doesn't seem to resolve extern calls on this file, which will prevent the *cwe_checker* from doing any meaningful analysis on the file.

Your second error means that the *cwe_checker* cannot find the standard configuration file that should be automatically installed. This should neither happen in the docker container nor on a local installation. Could you provide more context to the error? If this only happens for some files, could you provide an example? And could you open a separate issue for it? As a workaround, you can explicitly provide the (standard) config file via the `-config=src/config.json` command line flag

**Comment by frakman1** [comment] 2020-07-07 18:56
```bash
$docker pull fkiecad/cwe_checker:latest
latest: Pulling from fkiecad/cwe_checker
<...>
Digest: sha256:457e86f718173be8d5532f583cacaa946deee8cdd89be4c2160e42a9b517e29a
Status: Downloaded newer image for fkiecad/cwe_checker:latest
$docker run -it -v `pwd`:/opt fkiecad/cwe_checker /bin/bash
bap@4900de6e3b3f:~/cwe_checker$ bap --version
2.2.0-alpha+2e81951
bap@4900de6e3b3f:~/cwe_checker$ cwe_checker --version
0.3-dev
bap@4900de6e3b3f:~/cwe_checker$ bap --llvm-version
9.0
bap@4900de6e3b3f:~/cwe_checker$ cwe_checker /opt/ot-cli
INFO: Using standard configuration...
bap@4900de6e3b3f:~/cwe_checker$ 
```

Looks like there is no error anymore. So is the official stance that ARM is not really supported? It says in the README that it is. Perhaps that should be adjusted to spare others the hassle of trying.

**Comment by Enkelmann** [comment] 2020-07-07 20:15
Then I can close the issue again, thanks for checking. :-)

ARM (32bit) is supported by BAP and the *cwe_checker*. The problem is that BAP sometimes fails to to correctly parse calls to dynamic symbols like `malloc`. This is independent of the processor architecture (I have encountered it on different architectures), it may be related to certain ways dynamic symbols are encoded in an ELF file. I am still investigating it myself, so I can't say for sure. Most checks in the `cwe_checker` rely on these function calls getting parsed by BAP, so if this fails, these checks are useless. The `ot-cli` file you provided is such a file. You can detect this by running `bap BINARY -d | grep call`. If this doesn't print any explicit calls to dynamic symbols, BAP failed to resolve these calls.

**Closed by Enkelmann** 2020-07-07 20:15 UTC

**Comment by frakman1** [comment] 2020-07-07 20:21
Got it. Thanks.

I went through and ran `cwe_checker` against all my cross-compiled binaries and some of them actually returned some CWE results.
When the program returns with no errors back to the prompt, does that mean 'no errors found' or that it was unable to parse dynamic symbol calls?

**Comment by Enkelmann** [comment] 2020-07-08 05:16
Unfortunately, you cannot distinguish the good case from the bad case using only the *cwe_checker* output at the moment. :-( I have opened issue #68 for it, since we really should warn users if dynamic symbols couldn't be parsed.
