### ISSUE TITLE
uable to use it from the official docker version or locally

### ISSUE THREAD

**Issue by anzosasuke** [fkie-cad/cwe_checker#162] opened 2021-04-04 20:58 UTC
I am trying to use it for a project. Installed it through the docker and I cant get it to work.. 
Also i cant seem to install it locally.
error: Invalid value for '<binary>': No such file or directory (os error 2) Tried multiple way... May be my syntax is wrong Can u please give me some ideas

**Comment by Enkelmann** [comment] 2021-04-06 07:04
To download the latest docker image use
```
docker pull fkiecad/cwe_checker:latest
```
Use it with
```
docker run --rm -v /path/to/binary:/input fkiecad/cwe_checker /input
```
Keep in mind that the `/path/to/binary` needs to be an absolute path to an ELF binary, Docker does not accept relative paths there.

For the local installation issue I need more information about the system you try to install it on. Keep in mind that right now local installation should only work correctly on Linux. MacOS and Windows are not officially supported right now (e.g. there is a known issue that the install script moves the configuration files into the wrong folder).

Also, I am on vacation this week, so I won't be able to answer until next week.

**Comment by anzosasuke** [comment] 2021-04-06 20:16
it worked, but i am not able to use --json --out output.json,. Wanted to use that in ghidra as well.

**Comment by Enkelmann** [comment] 2021-04-07 10:33
You can use
```sh
docker run --rm -v /path/to/binary:/input fkiecad/cwe_checker /input --quiet --json > output.json
```
for that. The intended way would be to also mount the output file into the Docker container, but if the above command works for you, you don't need to read up on how to mount files into Docker. ;-)

**Comment by anzosasuke** [comment] 2021-04-07 14:58
Thank you so much. Yes, it did work on particular files but got this error on busybox file of the firmware

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `tid`", line: 6360885, column: 9)', src/caller/src/main.rs:300:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Enkelmann** [comment] 2021-04-12 06:24
This error message looks like a duplicate of issue #161, which we will try to fix this week. Please look there for updates on this problem.

Closing this issue.

**Closed by Enkelmann** 2021-04-12 06:24 UTC
