### ISSUE TITLE
[Map.add exn] got key already present

### ISSUE THREAD

**Issue by WilliamCoffeyTri** [fkie-cad/cwe_checker#64] opened 2020-06-15 15:37 UTC
Using the latest Master branch, Docker image built via the install.sh script.

BAP fails the cwe_checker pass against many targets with one of two issues. First was already reported here https://github.com/fkie-cad/cwe_checker/issues/61 and is being handled as a BAP bug. 

The second error is listed below. It seems to trigger on x86-32 targets from my limited-sample testing. In particular it was observed on these three file-type targets.

> ELF 32-bit LSB executable, intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.8, stripped
ELF 32-bit LSB executable, intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.8, not stripped	
PE32 executable (console) Intel 80386, for MS Windows

>pass "cwe-checker" failed in runtime with ("[Map.add_exn] got key already present"
										   (key 7381610))
Backtrace:
Raised at file "src/error.ml" (inlined), line 9, characters 14-30
Called from file "src/error.ml", line 11, characters 19-40
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 226, characters 10-90
Called from file "src/map.ml", line 226, characters 10-90
Called from file "src/map.ml", line 226, characters 10-90
Called from file "src/map.ml", line 226, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 226, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml", line 231, characters 10-90
Called from file "src/map.ml" (inlined), line 237, characters 4-90
Called from file "src/map.ml", line 1249, characters 11-140
Called from file "lib/bap_types/bap_ir.ml", line 1378, characters 6-89
Called from file "src/main.ml", line 98, characters 24-68
Called from file "src/main.ml", line 152, characters 12-35
Called from file "lib/bap/bap_project.ml", line 444, characters 56-59
Called from file "lib/bap/bap_project.ml", line 428, characters 20-32
Re-raised at file "lib/bap/bap_project.ml", line 433, characters 6-15
Called from file "lib/bap/bap_project.ml", line 469, characters 4-20
Called from file "lib/bap/bap_project.ml", line 480, characters 10-24

The error is consistent across all failing targets with the exception of the key number which is consistent on each run against a specific target.

And here is a sample invocation of cwe_checker as I am using it against one on one of the Juliet test binaries which is experiencing this issue.
`sudo docker run --rm -v ~/CWE476.exe:/tmp/input cwe-checker bap /tmp/input --pass=cwe-checker`

Please let me know if there's any obvious cause to this I'm missing or any additional information about the environment that would be valuable.

**Comment by ivg** [comment] 2020-06-15 15:52
@WilliamCoffeyTri, would it be possible to upload those files here? You can zip them to make github happy.

**Comment by WilliamCoffeyTri** [comment] 2020-06-15 17:28
[failing_binaries.zip](https://github.com/fkie-cad/cwe_checker/files/4781898/failing_binaries.zip)

These are three examples of binaries that fail with this issue; two exes from the Juliet test suite and an older version of vsftpd.

**Comment by Enkelmann** [comment] 2020-06-16 05:53
Could you also run `bap --version` and `bap --llvm-version` inside your docker container? We recently updated the underlying llvm version and I want to know which one your build is using.

I could not confirm the error with the official docker image (which is still using the older llvm version 6), but I think I know the error anyway. If I'm right, this should be easy to fix.

**Comment by Enkelmann** [comment] 2020-06-16 06:59
The new llvm version seems to also break our emulation plugins, so I will need some more time before I can push the fix to master. For the time being, using the official docker image `fkiecad/cwe_checker` should be a functioning workaround.

@ivg The bug is most likely triggered by encountering two terms with identical TIDs, which to my knowledge should not happen (and trigger an exception in the cwe_checker). Since it doesn't seem to trigger on the official cwe_checker docker image, it could be specific to the combination of llvm 8.0 with BAP 2.1.

**Comment by WilliamCoffeyTri** [comment] 2020-06-16 13:50
bap --llvm-version: 6.0
bap --version: 2.1.0-alpha

I will give the official image a try and see if it fares any better.

**Comment by ivg** [comment] 2020-06-16 14:45
@Enkelmann, you're absolutely right, tids shall not be duplicated so your `add_exn` was correct there. It looks like that it is a rather outdated version of bap (from the time when we didn't have commit sha in the version output). I tested on the BAP 2.1.0 release, using the following plugin,

```ocaml
(* file check_invariants.ml *)
open Core_kernel
open Bap.Std
open Bap_main

type error = Duplicating_tid of tid [@@deriving sexp]
exception Broken of error [@@deriving sexp]

let broken err = raise (Broken err)

let term_identifiers_are_unique program =
  let visitor = object inherit [Tid.Set.t] Term.visitor
    method! enter_term _ t visited =
      let tid = Term.tid t in
      if Set.mem visited tid
      then broken (Duplicating_tid tid);
      Set.add visited tid
  end in
  (visitor#run program Tid.Set.empty : Tid.Set.t) |> ignore

let check_invariants proj =
  term_identifiers_are_unique (Project.program proj)


let () = Extension.declare @@ fun ctxt ->
  Project.register_pass' check_invariants;
  Ok ()
```

and didn't get any violations on the provided input files.

**Comment by Enkelmann** [comment] 2020-06-30 06:39
@ivg I found a reproducible example of this error. Could you take a look at it? Run the cwe_checker in our latest docker image `fkiecad/cwe_checker:latest` with the attached binary as input:
```
docker run --rm -t -v /path/to/dhcp6c:/tmp/input fkiecad/cwe_checker:latest bap /tmp/input --pass=cwe-checker
```
The image uses BAP 2.1.0 with LLVM 9.

If this helps catching BAP bugs, I am inclined to keep the exception, as less BAP bugs benefits us more in the long run.

[dhcp6c.zip](https://github.com/fkie-cad/cwe_checker/files/4849837/dhcp6c.zip)

**Comment by ivg** [comment] 2020-06-30 11:09
I am on it!

**Comment by ivg** [comment] 2020-06-30 17:20
Status update. The culprit is that byteweight strikes a false positive function start directly into a delay slot of a conditional jump. And there are still some places in our disassembler that remember the old times when instructions were executed in the linear order (in other words that assume that we fall-through to the next address from a conditional jump). We will fix it soon, as a temporary workaround you can disable byteweight with `--no-byteweight`. 

> If this helps catching BAP bugs, I am inclined to keep the exception, as less BAP bugs benefits us more in the long run.

Yes, it is a good idea, it is better not to hide bugs :)

**Comment by Enkelmann** [comment] 2020-07-01 07:24
Thanks for looking! :-) Is there an issue for it on the BAP side I can link to?

**Comment by ivg** [comment] 2020-07-08 23:55
Yep, it is fixed now in https://github.com/BinaryAnalysisPlatform/bap/pull/1172
Feel free to close :)

**Comment by Enkelmann** [comment] 2020-07-09 12:11
Thanks! :-)
The docker image is also updated and should contain the fix.

**Closed by Enkelmann** 2020-07-09 12:11 UTC
